/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class PanelDigitador extends javax.swing.JFrame {

    /**
     * Creates new form PanelDigitador
     */
    String name="User Default";
    String convocatoria="Convacatoria Default";
    public PanelDigitador() {
        
    }
    public PanelDigitador(String username, String convoca){
        initComponents();
        name=username;
        this.convocatoria=convoca;
        WelcomeLabel.setText("¡Bienvenido "+name+"!");
        LabelConvocatoria.setText("Usted ha sido asignado a la convocatoria "+convocatoria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        jTabbedDigitador = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextNombres = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jTextCedula = new javax.swing.JTextField();
        jComboBoxGenero = new javax.swing.JComboBox();
        jComboBoxJornada = new javax.swing.JComboBox();
        jComboBoxMunicipio = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextLicUrl = new javax.swing.JTextField();
        jTextEspeUrl = new javax.swing.JTextField();
        jTextEspeTicUrl = new javax.swing.JTextField();
        jTextMaesUrl = new javax.swing.JTextField();
        jTextMaesTicUrl = new javax.swing.JTextField();
        jTextDocUrl = new javax.swing.JTextField();
        jTextDocTicUrl = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jRadioButtonLic1 = new javax.swing.JRadioButton();
        jRadioButtonLic2 = new javax.swing.JRadioButton();
        jRadioButtonEspe2 = new javax.swing.JRadioButton();
        jRadioButtonEspe1 = new javax.swing.JRadioButton();
        jRadioButtonEspeTic2 = new javax.swing.JRadioButton();
        jRadioButtonEspeTic1 = new javax.swing.JRadioButton();
        jRadioButtonMaes2 = new javax.swing.JRadioButton();
        jRadioButtonMaes1 = new javax.swing.JRadioButton();
        jRadioButtonMaesTic1 = new javax.swing.JRadioButton();
        jRadioButtonMaesTic2 = new javax.swing.JRadioButton();
        jRadioButtonDoc1 = new javax.swing.JRadioButton();
        jRadioButtonDoc2 = new javax.swing.JRadioButton();
        jRadioButtonDocTic1 = new javax.swing.JRadioButton();
        jRadioButtonDocTic2 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jTextLic = new javax.swing.JTextField();
        jTextEspe = new javax.swing.JTextField();
        jTextEspeTic = new javax.swing.JTextField();
        jTextMaes = new javax.swing.JTextField();
        jTextMaesTic = new javax.swing.JTextField();
        jTextDoc = new javax.swing.JTextField();
        jTextDocTic = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextCurso = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextCursoUrl = new javax.swing.JTextField();
        jComboBoxHorasCurso = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jRadioButton8_1 = new javax.swing.JRadioButton();
        jRadioButton8_2 = new javax.swing.JRadioButton();
        jRadioButton8_3 = new javax.swing.JRadioButton();
        jRadioButton1_3 = new javax.swing.JRadioButton();
        jRadioButton1_2 = new javax.swing.JRadioButton();
        jRadioButton1_1 = new javax.swing.JRadioButton();
        jRadioButton2_2 = new javax.swing.JRadioButton();
        jRadioButton2_3 = new javax.swing.JRadioButton();
        jRadioButton2_1 = new javax.swing.JRadioButton();
        jRadioButton3_2 = new javax.swing.JRadioButton();
        jRadioButton3_3 = new javax.swing.JRadioButton();
        jRadioButton3_1 = new javax.swing.JRadioButton();
        jRadioButton4_2 = new javax.swing.JRadioButton();
        jRadioButton4_3 = new javax.swing.JRadioButton();
        jRadioButton4_1 = new javax.swing.JRadioButton();
        jRadioButton5_2 = new javax.swing.JRadioButton();
        jRadioButton5_3 = new javax.swing.JRadioButton();
        jRadioButton5_1 = new javax.swing.JRadioButton();
        jRadioButton6_2 = new javax.swing.JRadioButton();
        jRadioButton6_3 = new javax.swing.JRadioButton();
        jRadioButton6_1 = new javax.swing.JRadioButton();
        jRadioButton7_2 = new javax.swing.JRadioButton();
        jRadioButton7_3 = new javax.swing.JRadioButton();
        jRadioButton7_1 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jTextIdioma = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jRadioButtonLee1 = new javax.swing.JRadioButton();
        jRadioButtonLee2 = new javax.swing.JRadioButton();
        jRadioButtonLee3 = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jRadioButtonEscribe1 = new javax.swing.JRadioButton();
        jRadioButtonEscribe2 = new javax.swing.JRadioButton();
        jRadioButtonEscribe3 = new javax.swing.JRadioButton();
        jRadioButtonHabla1 = new javax.swing.JRadioButton();
        jRadioButtonHabla2 = new javax.swing.JRadioButton();
        jRadioButtonHabla3 = new javax.swing.JRadioButton();
        jLabel40 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jComboBoxFormEst = new javax.swing.JComboBox();
        jComboBoxFormProf = new javax.swing.JComboBox();
        jComboBoxFormForm = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        LabelConfirmacion = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        WelcomeLabel = new javax.swing.JLabel();
        LabelConvocatoria = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digitador");
        setResizable(false);

        jTabbedDigitador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombres:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Apellidos:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cedula:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Genero:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("<html>Fecha Nacimiento:<html>");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Jornada:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Municipio:");

        jTextApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextApellidosActionPerformed(evt);
            }
        });

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));

        jComboBoxJornada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diurna", "Nocturna", "Ambas" }));

        jComboBoxMunicipio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cali", "Alcalá", "Andalucía", "Ansermanuevo", "Argelia", "Bolívar", "Buenaventura", "Buga", "Bugalagrande", "Caicedonia", "Candelaria", "Cartago", "Dagua", "Calima - El Darién", "El Águila", "El Cairo", "El Cerrito", "El Dovio", "Florida", "Ginebra", "Guacarí", "Jamundí", "La Cumbre", "La Unión", "La Victoria", "Obando", "Palmira", "Pradera", "Restrepo", "Riofrío", "Roldanillo", "San Pedro", "Sevilla", "Toro", "Trujillo", "Tuluá", "Ulloa", "Versalles", "Vijes", "Yotoco", "Yumbo", "Zarzal", " ", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxJornada, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextCedula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextApellidos)
                            .addComponent(jComboBoxMunicipio, 0, 190, Short.MAX_VALUE))))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextCedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedDigitador.addTab("Datos Personales", jPanel1);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Licenciado en educacion o areas afines:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Especializacion:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Especialización en áreas afines a TIC:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Maestria:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Maestría en áreas afines a TIC:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Doctorado:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Doctorado en áreas afines a TIC:");

        jTextLicUrl.setEnabled(false);
        jTextLicUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLicUrlActionPerformed(evt);
            }
        });

        jTextEspeUrl.setEnabled(false);

        jTextEspeTicUrl.setEnabled(false);

        jTextMaesUrl.setEnabled(false);

        jTextMaesTicUrl.setEnabled(false);

        jTextDocUrl.setEnabled(false);

        jTextDocTicUrl.setEnabled(false);
        jTextDocTicUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDocTicUrlActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel19.setText("NIVEL");

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel20.setText("UBICACION SOPORTE");

        buttonGroup1.add(jRadioButtonLic1);
        jRadioButtonLic1.setText("Si");
        jRadioButtonLic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLic1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonLic2);
        jRadioButtonLic2.setSelected(true);
        jRadioButtonLic2.setText("No");
        jRadioButtonLic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLic2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonEspe2);
        jRadioButtonEspe2.setSelected(true);
        jRadioButtonEspe2.setText("No");
        jRadioButtonEspe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEspe2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonEspe1);
        jRadioButtonEspe1.setText("Si");
        jRadioButtonEspe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEspe1ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButtonEspeTic2);
        jRadioButtonEspeTic2.setSelected(true);
        jRadioButtonEspeTic2.setText("No");
        jRadioButtonEspeTic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEspeTic2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButtonEspeTic1);
        jRadioButtonEspeTic1.setText("Si");
        jRadioButtonEspeTic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEspeTic1ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButtonMaes2);
        jRadioButtonMaes2.setSelected(true);
        jRadioButtonMaes2.setText("No");
        jRadioButtonMaes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaes2ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButtonMaes1);
        jRadioButtonMaes1.setText("Si");
        jRadioButtonMaes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaes1ActionPerformed(evt);
            }
        });

        buttonGroup5.add(jRadioButtonMaesTic1);
        jRadioButtonMaesTic1.setText("Si");
        jRadioButtonMaesTic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaesTic1ActionPerformed(evt);
            }
        });

        buttonGroup5.add(jRadioButtonMaesTic2);
        jRadioButtonMaesTic2.setSelected(true);
        jRadioButtonMaesTic2.setText("No");
        jRadioButtonMaesTic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaesTic2ActionPerformed(evt);
            }
        });

        buttonGroup6.add(jRadioButtonDoc1);
        jRadioButtonDoc1.setText("Si");
        jRadioButtonDoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDoc1ActionPerformed(evt);
            }
        });

        buttonGroup6.add(jRadioButtonDoc2);
        jRadioButtonDoc2.setSelected(true);
        jRadioButtonDoc2.setText("No");
        jRadioButtonDoc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDoc2ActionPerformed(evt);
            }
        });

        buttonGroup7.add(jRadioButtonDocTic1);
        jRadioButtonDocTic1.setText("Si");
        jRadioButtonDocTic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDocTic1ActionPerformed(evt);
            }
        });

        buttonGroup7.add(jRadioButtonDocTic2);
        jRadioButtonDocTic2.setSelected(true);
        jRadioButtonDocTic2.setText("No");
        jRadioButtonDocTic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDocTic2ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel21.setText("TITULO");

        jTextLic.setEnabled(false);

        jTextEspe.setEnabled(false);

        jTextEspeTic.setEnabled(false);

        jTextMaes.setEnabled(false);

        jTextMaesTic.setEnabled(false);

        jTextDoc.setEnabled(false);

        jTextDocTic.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonMaes1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonMaes2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextMaes, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonMaesTic1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonMaesTic2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextMaesTic, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonDoc1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonDoc2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonDocTic1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonDocTic2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextDocTic, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonEspeTic1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonEspeTic2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextEspeTic, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextDocUrl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTextMaesTicUrl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextMaesUrl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextEspeTicUrl)
                            .addComponent(jTextDocTicUrl)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonEspe1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonEspe2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextEspe, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonLic1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonLic2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextLic, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextLicUrl)
                            .addComponent(jTextEspeUrl))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonEspeTic1)
                        .addComponent(jRadioButtonEspeTic2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextLicUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonLic1)
                            .addComponent(jRadioButtonLic2)
                            .addComponent(jTextLic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextEspeUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonEspe1)
                            .addComponent(jRadioButtonEspe2)
                            .addComponent(jTextEspe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextEspeTicUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextEspeTic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jTextMaesUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonMaes1)
                        .addComponent(jRadioButtonMaes2)
                        .addComponent(jTextMaes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jTextMaesTicUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonMaesTic1)
                        .addComponent(jRadioButtonMaesTic2)
                        .addComponent(jTextMaesTic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jTextDocUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonDoc1)
                        .addComponent(jRadioButtonDoc2)
                        .addComponent(jTextDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonDocTic1)
                            .addComponent(jRadioButtonDocTic2)
                            .addComponent(jTextDocTic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextDocTicUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedDigitador.addTab("Formacion", jPanel2);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Curso:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Horas:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("URL Soporte:");

        jComboBoxHorasCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Curso TIC minimo 40 horas", "Curso TIC hasta 90 horas", "Curso TIC hasta 140 horas", "Curso TIC mas de 40 horas" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCurso)
                            .addComponent(jComboBoxHorasCurso, 0, 200, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jTextCursoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(552, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBoxHorasCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextCursoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedDigitador.addTab("Formacion en TIC", jPanel3);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Conocimiento y manejo de herramientas ofimaticas:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel26.setText("CONOCIMIENTO");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Conocimiento y manejo de herramientas Web 2:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Conocimiento herramientas de edición multimedia:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Experiencia en desarrollo de contenidos educativos digitales:");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Experiencia en desarrollo de libros de texto digital:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Experiencia en procesos de e-learning:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Experiencia en gestión de proyectos educativos TIC:");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Experiencia en desarrollo de elementos de evaluación de competencias:");

        jLabel34.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel34.setText("NIVEL");

        buttonGroup15.add(jRadioButton8_1);
        jRadioButton8_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton8_1.setText("Regular");

        buttonGroup15.add(jRadioButton8_2);
        jRadioButton8_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton8_2.setText("Bueno");

        buttonGroup15.add(jRadioButton8_3);
        jRadioButton8_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton8_3.setText("Muy Bueno");

        buttonGroup8.add(jRadioButton1_3);
        jRadioButton1_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1_3.setText("Muy Bueno");

        buttonGroup8.add(jRadioButton1_2);
        jRadioButton1_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1_2.setText("Bueno");

        buttonGroup8.add(jRadioButton1_1);
        jRadioButton1_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1_1.setText("Regular");

        buttonGroup9.add(jRadioButton2_2);
        jRadioButton2_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2_2.setText("Bueno");

        buttonGroup9.add(jRadioButton2_3);
        jRadioButton2_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2_3.setText("Muy Bueno");

        buttonGroup9.add(jRadioButton2_1);
        jRadioButton2_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2_1.setText("Regular");

        buttonGroup10.add(jRadioButton3_2);
        jRadioButton3_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3_2.setText("Bueno");

        buttonGroup10.add(jRadioButton3_3);
        jRadioButton3_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3_3.setText("Muy Bueno");

        buttonGroup10.add(jRadioButton3_1);
        jRadioButton3_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3_1.setText("Regular");

        buttonGroup11.add(jRadioButton4_2);
        jRadioButton4_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4_2.setText("Bueno");

        buttonGroup11.add(jRadioButton4_3);
        jRadioButton4_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4_3.setText("Muy Bueno");

        buttonGroup11.add(jRadioButton4_1);
        jRadioButton4_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4_1.setText("Regular");

        buttonGroup12.add(jRadioButton5_2);
        jRadioButton5_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton5_2.setText("Bueno");

        buttonGroup12.add(jRadioButton5_3);
        jRadioButton5_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton5_3.setText("Muy Bueno");

        buttonGroup12.add(jRadioButton5_1);
        jRadioButton5_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton5_1.setText("Regular");

        buttonGroup13.add(jRadioButton6_2);
        jRadioButton6_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton6_2.setText("Bueno");

        buttonGroup13.add(jRadioButton6_3);
        jRadioButton6_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton6_3.setText("Muy Bueno");

        buttonGroup13.add(jRadioButton6_1);
        jRadioButton6_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton6_1.setText("Regular");

        buttonGroup14.add(jRadioButton7_2);
        jRadioButton7_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton7_2.setText("Bueno");

        buttonGroup14.add(jRadioButton7_3);
        jRadioButton7_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton7_3.setText("Muy Bueno");

        buttonGroup14.add(jRadioButton7_1);
        jRadioButton7_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton7_1.setText("Regular");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton7_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton7_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton7_3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton6_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton6_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton6_3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton5_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton5_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton5_3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton4_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton4_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton4_3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton3_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton3_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton3_3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton2_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2_3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton1_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1_3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton8_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton8_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton8_3)))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel34)
                        .addGap(129, 129, 129))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel26)
                                                                    .addComponent(jLabel34))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel25))
                                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jRadioButton1_1)
                                                                .addComponent(jRadioButton1_2)
                                                                .addComponent(jRadioButton1_3)))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel27))
                                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jRadioButton2_1)
                                                        .addComponent(jRadioButton2_2)
                                                        .addComponent(jRadioButton2_3)))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel28))
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jRadioButton3_1)
                                                .addComponent(jRadioButton3_2)
                                                .addComponent(jRadioButton3_3)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel29))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton4_1)
                                        .addComponent(jRadioButton4_2)
                                        .addComponent(jRadioButton4_3)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton5_1)
                                .addComponent(jRadioButton5_2)
                                .addComponent(jRadioButton5_3)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton6_1)
                        .addComponent(jRadioButton6_2)
                        .addComponent(jRadioButton6_3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton7_1)
                    .addComponent(jRadioButton7_2)
                    .addComponent(jRadioButton7_3)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton8_1)
                        .addComponent(jRadioButton8_2)
                        .addComponent(jRadioButton8_3)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedDigitador.addTab("Conocimientos Especificos", jPanel4);

        jLabel35.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel35.setText("IDIOMA");

        jTextIdioma.setEnabled(false);
        jTextIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdiomaActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel36.setText("NIVEL");

        buttonGroup16.add(jRadioButtonLee1);
        jRadioButtonLee1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonLee1.setText("Regular");
        jRadioButtonLee1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonLee1.setEnabled(false);

        buttonGroup16.add(jRadioButtonLee2);
        jRadioButtonLee2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonLee2.setText("Bueno");
        jRadioButtonLee2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonLee2.setEnabled(false);

        buttonGroup16.add(jRadioButtonLee3);
        jRadioButtonLee3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonLee3.setText("Muy Bueno");
        jRadioButtonLee3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonLee3.setEnabled(false);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Lee:");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Escribe:");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Habla:");

        buttonGroup17.add(jRadioButtonEscribe1);
        jRadioButtonEscribe1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonEscribe1.setText("Regular");
        jRadioButtonEscribe1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonEscribe1.setEnabled(false);

        buttonGroup17.add(jRadioButtonEscribe2);
        jRadioButtonEscribe2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonEscribe2.setText("Bueno");
        jRadioButtonEscribe2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonEscribe2.setEnabled(false);

        buttonGroup17.add(jRadioButtonEscribe3);
        jRadioButtonEscribe3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonEscribe3.setText("Muy Bueno");
        jRadioButtonEscribe3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonEscribe3.setEnabled(false);

        buttonGroup18.add(jRadioButtonHabla1);
        jRadioButtonHabla1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonHabla1.setText("Regular");
        jRadioButtonHabla1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonHabla1.setEnabled(false);

        buttonGroup18.add(jRadioButtonHabla2);
        jRadioButtonHabla2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonHabla2.setText("Bueno");
        jRadioButtonHabla2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonHabla2.setEnabled(false);

        buttonGroup18.add(jRadioButtonHabla3);
        jRadioButtonHabla3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonHabla3.setText("Muy Bueno");
        jRadioButtonHabla3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonHabla3.setEnabled(false);

        jLabel40.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel40.setText("CATEGORIA");

        buttonGroup19.add(jRadioButton1);
        jRadioButton1.setText("Si");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup19.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jRadioButtonEscribe1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonEscribe2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonEscribe3))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jRadioButtonHabla1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonHabla2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonHabla3))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonLee1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonLee2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonLee3))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextIdioma))))
                    .addComponent(jLabel40)
                    .addComponent(jLabel35))
                .addContainerGap(472, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jTextIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonLee1)
                    .addComponent(jRadioButtonLee2)
                    .addComponent(jRadioButtonLee3)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEscribe1)
                    .addComponent(jRadioButtonEscribe2)
                    .addComponent(jRadioButtonEscribe3)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonHabla1)
                    .addComponent(jRadioButtonHabla2)
                    .addComponent(jRadioButtonHabla3)
                    .addComponent(jLabel39))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedDigitador.addTab("Idiomas", jPanel5);

        jLabel41.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel41.setText("CATEGORIA");

        jLabel42.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel42.setText("EXPERIENCIA ACADEMICA");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Formador TIC a estudiantes");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Formador TIC a profesores");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Formador TIC de formadores");

        jComboBoxFormEst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxFormEst.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No tiene Experiencia", "De 1 a 2 años", "De 2 a 3 años", "De 3 a 5 años", "Mas de 5 años" }));

        jComboBoxFormProf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxFormProf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No tiene Experiencia", "De 80 a 200 horas", "De 200 a 300 horas", "De 300 a 450 horas", "Mas de 450 horas" }));

        jComboBoxFormForm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxFormForm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No tiene Experiencia", "De 80 a 120 horas", "Mas de 120 horas" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel41)))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxFormProf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxFormEst, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxFormForm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jComboBoxFormEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jComboBoxFormProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jComboBoxFormForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        jTabbedDigitador.addTab("Experiencia", jPanel6);

        LabelConfirmacion.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        LabelConfirmacion.setText("Desea Registrar al Aspirante XXX a la Convocatoria XXX ?");

        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/Add-Asp-icon.png"))); // NOI18N
        jButtonRegistrar.setText("REGISTRAR");
        jButtonRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/Back-Asp-icon.png"))); // NOI18N
        jButtonCancelar.setText("REGISTRAR OTRO ASPIRANTE");
        jButtonCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LabelConfirmacion)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistrar)
                .addGap(30, 30, 30)
                .addComponent(jButtonCancelar)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedDigitador.addTab("REGISTRAR", jPanel7);

        WelcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        WelcomeLabel.setText("¡Bienvenido !");

        LabelConvocatoria.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        LabelConvocatoria.setText("Usted esta asignado a la convocatoria");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setText("A continuacion se presenta los formularios de registro de aspirantes");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/LogoSinFondo2.png"))); // NOI18N

        jButtonLogout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/Login-out-icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedDigitador)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(LabelConvocatoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLogout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(WelcomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel11)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WelcomeLabel)
                        .addGap(29, 29, 29)
                        .addComponent(LabelConvocatoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel11)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jTabbedDigitador)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextApellidosActionPerformed

    private void jRadioButtonLic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLic1ActionPerformed
      
        jTextLic.setEnabled(true);
        jTextLicUrl.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonLic1ActionPerformed

    private void jRadioButtonEspe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEspe1ActionPerformed
        jTextEspe.setEnabled(true);
        jTextEspeUrl.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonEspe1ActionPerformed

    private void jRadioButtonEspeTic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEspeTic1ActionPerformed
        // TODO add your handling code here:
        jTextEspeTic.setEnabled(true);
        jTextEspeTicUrl.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonEspeTic1ActionPerformed

    private void jRadioButtonMaes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaes1ActionPerformed
        // TODO add your handling code here:
        jTextMaes.setEnabled(true);
        jTextMaesUrl.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonMaes1ActionPerformed

    private void jRadioButtonMaesTic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaesTic1ActionPerformed
        // TODO add your handling code here:
        jTextMaesTic.setEnabled(true);
        jTextMaesTicUrl.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonMaesTic1ActionPerformed

    private void jRadioButtonDoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDoc1ActionPerformed
        // TODO add your handling code here:
        jTextDoc.setEnabled(true);
        jTextDocUrl.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonDoc1ActionPerformed

    private void jRadioButtonDocTic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDocTic1ActionPerformed
        // TODO add your handling code here:
        jTextDocTic.setEnabled(true);
        jTextDocTicUrl.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonDocTic1ActionPerformed

    private void jTextLicUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLicUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLicUrlActionPerformed

    private void jTextDocTicUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDocTicUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDocTicUrlActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "NOMbre: "+jRadioButton1_1.getName());
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jTextIdioma.setEnabled(true);
        jRadioButtonLee1.setEnabled(true);
        jRadioButtonLee2.setEnabled(true);
        jRadioButtonLee3.setEnabled(true);
        jRadioButtonEscribe1.setEnabled(true);
        jRadioButtonEscribe2.setEnabled(true);
        jRadioButtonEscribe3.setEnabled(true);
        jRadioButtonHabla1.setEnabled(true);
        jRadioButtonHabla2.setEnabled(true);
        jRadioButtonHabla3.setEnabled(true);
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jTextIdioma.setEnabled(false);
        jRadioButtonLee1.setEnabled(false);
        jRadioButtonLee2.setEnabled(false);
        jRadioButtonLee3.setEnabled(false);
        jRadioButtonEscribe1.setEnabled(false);
        jRadioButtonEscribe2.setEnabled(false);
        jRadioButtonEscribe3.setEnabled(false);
        jRadioButtonHabla1.setEnabled(false);
        jRadioButtonHabla2.setEnabled(false);
        jRadioButtonHabla3.setEnabled(false);   
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdiomaActionPerformed

    private void jRadioButtonLic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLic2ActionPerformed
        // TODO add your handling code here:
        jTextLic.setEnabled(false);
        jTextLicUrl.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonLic2ActionPerformed

    private void jRadioButtonEspe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEspe2ActionPerformed
        // TODO add your handling code here:
        jTextEspe.setEnabled(false);
        jTextEspeUrl.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonEspe2ActionPerformed

    private void jRadioButtonEspeTic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEspeTic2ActionPerformed
        // TODO add your handling code here:
        jTextEspeTic.setEnabled(false);
        jTextEspeTicUrl.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonEspeTic2ActionPerformed

    private void jRadioButtonMaes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaes2ActionPerformed
        // TODO add your handling code here:
        jTextMaes.setEnabled(false);
        jTextMaesUrl.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonMaes2ActionPerformed

    private void jRadioButtonMaesTic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaesTic2ActionPerformed
        // TODO add your handling code here:
        jTextMaesTic.setEnabled(false);
        jTextMaesTicUrl.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonMaesTic2ActionPerformed

    private void jRadioButtonDoc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDoc2ActionPerformed
        // TODO add your handling code here:
        jTextDoc.setEnabled(false);
        jTextDocUrl.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonDoc2ActionPerformed

    private void jRadioButtonDocTic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDocTic2ActionPerformed
        // TODO add your handling code here:
        jTextDocTic.setEnabled(false);
        jTextDocTicUrl.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonDocTic2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDigitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDigitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDigitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDigitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDigitador("Nelson", "ConvocatoriaDocente").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelConfirmacion;
    private javax.swing.JLabel LabelConvocatoria;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox jComboBoxFormEst;
    private javax.swing.JComboBox jComboBoxFormForm;
    private javax.swing.JComboBox jComboBoxFormProf;
    private javax.swing.JComboBox jComboBoxGenero;
    private javax.swing.JComboBox jComboBoxHorasCurso;
    private javax.swing.JComboBox jComboBoxJornada;
    private javax.swing.JComboBox jComboBoxMunicipio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton1_1;
    private javax.swing.JRadioButton jRadioButton1_2;
    private javax.swing.JRadioButton jRadioButton1_3;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton2_1;
    private javax.swing.JRadioButton jRadioButton2_2;
    private javax.swing.JRadioButton jRadioButton2_3;
    private javax.swing.JRadioButton jRadioButton3_1;
    private javax.swing.JRadioButton jRadioButton3_2;
    private javax.swing.JRadioButton jRadioButton3_3;
    private javax.swing.JRadioButton jRadioButton4_1;
    private javax.swing.JRadioButton jRadioButton4_2;
    private javax.swing.JRadioButton jRadioButton4_3;
    private javax.swing.JRadioButton jRadioButton5_1;
    private javax.swing.JRadioButton jRadioButton5_2;
    private javax.swing.JRadioButton jRadioButton5_3;
    private javax.swing.JRadioButton jRadioButton6_1;
    private javax.swing.JRadioButton jRadioButton6_2;
    private javax.swing.JRadioButton jRadioButton6_3;
    private javax.swing.JRadioButton jRadioButton7_1;
    private javax.swing.JRadioButton jRadioButton7_2;
    private javax.swing.JRadioButton jRadioButton7_3;
    private javax.swing.JRadioButton jRadioButton8_1;
    private javax.swing.JRadioButton jRadioButton8_2;
    private javax.swing.JRadioButton jRadioButton8_3;
    private javax.swing.JRadioButton jRadioButtonDoc1;
    private javax.swing.JRadioButton jRadioButtonDoc2;
    private javax.swing.JRadioButton jRadioButtonDocTic1;
    private javax.swing.JRadioButton jRadioButtonDocTic2;
    private javax.swing.JRadioButton jRadioButtonEscribe1;
    private javax.swing.JRadioButton jRadioButtonEscribe2;
    private javax.swing.JRadioButton jRadioButtonEscribe3;
    private javax.swing.JRadioButton jRadioButtonEspe1;
    private javax.swing.JRadioButton jRadioButtonEspe2;
    private javax.swing.JRadioButton jRadioButtonEspeTic1;
    private javax.swing.JRadioButton jRadioButtonEspeTic2;
    private javax.swing.JRadioButton jRadioButtonHabla1;
    private javax.swing.JRadioButton jRadioButtonHabla2;
    private javax.swing.JRadioButton jRadioButtonHabla3;
    private javax.swing.JRadioButton jRadioButtonLee1;
    private javax.swing.JRadioButton jRadioButtonLee2;
    private javax.swing.JRadioButton jRadioButtonLee3;
    private javax.swing.JRadioButton jRadioButtonLic1;
    private javax.swing.JRadioButton jRadioButtonLic2;
    private javax.swing.JRadioButton jRadioButtonMaes1;
    private javax.swing.JRadioButton jRadioButtonMaes2;
    private javax.swing.JRadioButton jRadioButtonMaesTic1;
    private javax.swing.JRadioButton jRadioButtonMaesTic2;
    private javax.swing.JTabbedPane jTabbedDigitador;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextCurso;
    private javax.swing.JTextField jTextCursoUrl;
    private javax.swing.JTextField jTextDoc;
    private javax.swing.JTextField jTextDocTic;
    private javax.swing.JTextField jTextDocTicUrl;
    private javax.swing.JTextField jTextDocUrl;
    private javax.swing.JTextField jTextEspe;
    private javax.swing.JTextField jTextEspeTic;
    private javax.swing.JTextField jTextEspeTicUrl;
    private javax.swing.JTextField jTextEspeUrl;
    private javax.swing.JTextField jTextIdioma;
    private javax.swing.JTextField jTextLic;
    private javax.swing.JTextField jTextLicUrl;
    private javax.swing.JTextField jTextMaes;
    private javax.swing.JTextField jTextMaesTic;
    private javax.swing.JTextField jTextMaesTicUrl;
    private javax.swing.JTextField jTextMaesUrl;
    private javax.swing.JTextField jTextNombres;
    // End of variables declaration//GEN-END:variables
}
