/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import almacenamiento.controlador.ControlReporte;
import java.awt.Dimension;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import org.jfree.chart.*;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author daniel
 */
public class PanelCoordinador extends javax.swing.JFrame {

    private ControlReporte controlador;
    private int codigoConvo;
    private String name;
    private Connection conn;
    /**
     * Creates new form PanelCoordinador
     */
    /*public PanelCoordinador() {
        initComponents();
        setResizable(false);
        
    }*/
    
    public PanelCoordinador(String nombre ,int codigoConvocatoria ,Connection conn){
        initComponents();
        setResizable(false);
        this.setTitle("Panel de Coordinacion");
        codigoConvo = codigoConvocatoria;
        this.conn=conn;
        controlador = new ControlReporte(this.conn,codigoConvo);
        lbTitulo.setText("Bienvenido "+nombre+"!");
        name = nombre;
        System.out.println("codigo convo:"+codigoConvo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btValidacion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btInscritos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btSeleccionados = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btMejorPunto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btJornada = new javax.swing.JButton();
        btSexo = new javax.swing.JButton();
        btReporteCiudad = new javax.swing.JButton();
        btCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbTitulo.setText("Bienvenido user!");

        jLabel2.setText("Aqui encontrara un panel que le permitira acceder a los diferentes reportes de informacion  ");

        jLabel3.setText("y a la validacion de informacion de un aspirante");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/LogoSinFondo2.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel5.setText("Validacion de Usuarios: ");

        btValidacion.setText("Ingresar");
        btValidacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValidacionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel6.setText("Reportes");

        btInscritos.setText("Ir");
        btInscritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInscritosActionPerformed(evt);
            }
        });

        jLabel1.setText("Total de Aspirantes inscritos:");

        jLabel7.setText("Total de Aspirantes Seleccionados:");

        btSeleccionados.setText("Ir");
        btSeleccionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeleccionadosActionPerformed(evt);
            }
        });

        jLabel8.setText("Cinco mejores puntajes: ");

        btMejorPunto.setText("Ir");
        btMejorPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMejorPuntoActionPerformed(evt);
            }
        });

        jLabel9.setText("Porcentaje de inscritos por ciudad:");

        jLabel10.setText("Numero de hombres y mujeres inscritos:");

        jLabel11.setText("Total de maestros por jornada:");

        btJornada.setText("Ir");
        btJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJornadaActionPerformed(evt);
            }
        });

        btSexo.setText("Ir");

        btReporteCiudad.setText("Ir");
        btReporteCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReporteCiudadActionPerformed(evt);
            }
        });

        btCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/Login-out-icon.png"))); // NOI18N
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(btValidacion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
            .addGroup(layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btMejorPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(103, 103, 103)
                                .addComponent(btInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(103, 103, 103)
                                .addComponent(btReporteCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(lbTitulo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btCerrar)
                                        .addGap(37, 37, 37)))))
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lbTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCerrar)
                        .addGap(1, 1, 1)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btValidacion))
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btInscritos)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(btSeleccionados)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMejorPunto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btReporteCiudad)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(btSexo)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btJornada))))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValidacionActionPerformed
        // TODO add your handling code here:
        VistaElejirAspirante vista  = new VistaElejirAspirante(name, codigoConvo, conn);
        vista.setVisible(true);
        System.out.println("vista iniciada");
        
    }//GEN-LAST:event_btValidacionActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        // TODO add your handling code here:
        controlador.cerrarConexionBD();
        System.exit(0);
    }//GEN-LAST:event_btCerrarActionPerformed

    private void btMejorPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMejorPuntoActionPerformed
        //Metodo para obtener los 5 mejores puntajes
        String[][] resultado = controlador.cincoMejores();
        if(resultado==null){
            JOptionPane.showMessageDialog(this, "No hay aspirantes inscritos en esta convocatoria","Error!",JOptionPane.ERROR_MESSAGE);
        }else{
                String[] nombresColumnas = {"NOMBRES","APELLIDOS","CEDULA","MUNICIPIO"};
                JTable ventana = new JTable(resultado,nombresColumnas);
                ventana.setEnabled(false);
                Dimension d = ventana.getPreferredSize();
                
                JScrollPane panel = new JScrollPane(ventana);
                panel.setPreferredSize(new Dimension(d.width+9,ventana.getRowHeight()*7+1));
                JOptionPane.showMessageDialog(this, panel,"Cinco Mejores Puntajes",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btMejorPuntoActionPerformed

    private void btJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJornadaActionPerformed
        //Metodo para consultar el total de inscritos por jornada
        String[][] resultado = controlador.totalPorJornada();
        if(resultado==null){
            JOptionPane.showMessageDialog(this, "No hay aspirantes inscritos en esta convocatoria","Error!",JOptionPane.ERROR_MESSAGE);
        }else{
                String[] nombresColumnas = {"JORNADA","TOTAL DE INSCRITOS"};
                JTable ventana = new JTable(resultado,nombresColumnas);
                ventana.setEnabled(false);
                Dimension d = ventana.getPreferredSize();
                
                JScrollPane panel = new JScrollPane(ventana);
                panel.setPreferredSize(new Dimension(d.width+50,ventana.getRowHeight()*5+1));
                JOptionPane.showMessageDialog(this, panel,"Total de Inscritos por Jornada",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btJornadaActionPerformed
    
	private void btSexoActionPerformed(java.awt.event.ActionEvent evt) {                                       
        int hombres=0;
        int mujeres=0;
        hombres=controlador.hombresInscritos();
        mujeres=controlador.mujeresInscritas();
        JOptionPane.showMessageDialog(this, "Total de inscritos:\nMujeres: "+mujeres+"\nHombres: "+hombres);
    }     
    
    private void btSeleccionadosActionPerformed(java.awt.event.ActionEvent evt) {                                                
        ReporteSeleccionados selecc = new ReporteSeleccionados(controlador.numSeleccionados(), controlador.seleccionados());
        selecc.setVisible(true);
    } 

    private void btInscritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInscritosActionPerformed

        String[][] resultado = controlador.listadoAsp();
        if(resultado==null){
            JOptionPane.showMessageDialog(this, "No hay aspirantes inscritos en esta convocatoria","Error!",JOptionPane.ERROR_MESSAGE);
        }else{
                String[] nombresColumnas = {"NOMBRES","APELLIDOS","CEDULA","MUNICIPIO"};
                JTable ventana = new JTable(resultado,nombresColumnas);
                ventana.setEnabled(false);
                Dimension d = ventana.getPreferredSize();
                
                JScrollPane panel = new JScrollPane(ventana);
                panel.setPreferredSize(new Dimension(d.width+9,ventana.getRowHeight()*7+1));
                JOptionPane.showMessageDialog(this, panel,"Aspirantes",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btInscritosActionPerformed

    private void btReporteCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReporteCiudadActionPerformed
        ChartPanel panel;
        JFreeChart chart;
        DefaultCategoryDataset datos = new DefaultCategoryDataset();
        String[][] resultado = controlador.conteoMunic();
        String municipio = "municipios";
        String numeroAsp = "numero de Aspirantes";
        
        if(resultado==null){
            JOptionPane.showMessageDialog(this, "No hay aspirantes inscritos en esta convocatoria","Error!",JOptionPane.ERROR_MESSAGE);
        }else{
                for(int i=0; i<resultado.length; i++){
                    datos.addValue(Integer.parseInt(resultado[i][1]), resultado[i][0], resultado[i][0]);
                }
                chart = ChartFactory.createBarChart("Conteo de municipios", "Municipios", 
                                                        "Cantidad", datos,
                                                        PlotOrientation.VERTICAL,
                                                        true,
                                                        true,
                                                        true);
                CategoryPlot plot = (CategoryPlot) chart.getPlot();
                plot.setDomainGridlinesVisible(true);
                panel = new ChartPanel(chart);
                panel.setBounds(5, 10, 410, 350);   
                Dimension d = panel.getPreferredSize();
                JScrollPane panelScroll = new JScrollPane(panel);
                panelScroll.setPreferredSize(new Dimension(d.width+9,panel.getMaximumDrawHeight()));
                JOptionPane.showMessageDialog(this, panel,"Conteo de municipios",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btReporteCiudadActionPerformed


    /**
     * @param args the command line arguments
     *//*
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         *//*
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PanelCoordinador().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btInscritos;
    private javax.swing.JButton btJornada;
    private javax.swing.JButton btMejorPunto;
    private javax.swing.JButton btReporteCiudad;
    private javax.swing.JButton btSeleccionados;
    private javax.swing.JButton btSexo;
    private javax.swing.JButton btValidacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
