/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentacion;
import javax.swing.JOptionPane;
import proceso.*;
import almacenamiento.controlador.*;

/**
 * Clase VistaCrearUsuario. Clase con la interfaz grafica para 
 * crear un usario nuevo en el sistema
 * @author SISCONDOC Development team
 */
public class VistaCrearUsuario extends javax.swing.JFrame {

    UserController objControl;
    ConvocatoriaController objConvocatoria;
    boolean hayConvocatorias;
    String[] nomConvocatorias;
    
    
    /**
     * Constructor de la clase
     * @param userControler Se le introduce un objeto de la clase UserController
     * @param convController Se le introduce un objeto de la clase ConvocatoriaController
     */
    public VistaCrearUsuario(UserController userControler, ConvocatoriaController convController) {
        initComponents();
        comboPerfil.setSelectedIndex(2);
        objControl=userControler;
        objConvocatoria=convController;
        consultaConvocatorias();
        muestraConvocatorias();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblLogo = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        lblMail = new javax.swing.JLabel();
        txtNomUsuario = new javax.swing.JTextField();
        lblNomUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        comboPerfil = new javax.swing.JComboBox();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        comboConvocatoria = new javax.swing.JComboBox();
        lblAdvertencia = new javax.swing.JLabel();
        lblConvocatoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel Administrador: Crear Usuario");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("Crear Usuario");

        lblDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescripcion.setText("Aquí encontrará el formulario de creación de usuarios");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/LogoSinFondo2.png"))); // NOI18N

        lblNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombres.setText("Nombres:");

        lblApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblApellidos.setText("Apellidos:");

        lblMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMail.setText("E-mail:");

        lblNomUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomUsuario.setText("Nombre de Usuario:");

        lblContrasena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblContrasena.setText("Contraseña:");

        lblCedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCedula.setText("Número de cédula:");

        lblPerfil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPerfil.setText("Perfil:");

        comboPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Digitador", "Coordinador", "Administrador" }));
        comboPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPerfilActionPerformed(evt);
            }
        });

        btnCrear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblAdvertencia.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblAdvertencia.setForeground(new java.awt.Color(255, 0, 0));
        lblAdvertencia.setText("*No existen convocatorias, por lo tanto no se pueden crear digitadores o coordinadores");

        lblConvocatoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConvocatoria.setText("Convocatoria:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblContrasena)
                                        .addGap(142, 142, 142)
                                        .addComponent(txtContrasena))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNomUsuario)
                                        .addGap(89, 89, 89)
                                        .addComponent(txtNomUsuario))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMail)
                                        .addGap(181, 181, 181)
                                        .addComponent(txtMail))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblApellidos)
                                                .addGap(160, 160, 160))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblNombres)
                                                .addGap(159, 159, 159)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(3, 3, 3))
                                            .addComponent(txtApellidos))))
                                .addGap(263, 263, 263))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCrear)
                                .addGap(42, 42, 42)
                                .addComponent(btnCancelar)
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCedula)
                                    .addComponent(lblConvocatoria)
                                    .addComponent(lblPerfil))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitulo)
                                    .addComponent(lblDescripcion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLogo)))
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(lblDescripcion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMail)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomUsuario)
                    .addComponent(txtNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerfil)
                    .addComponent(comboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConvocatoria)
                    .addComponent(comboConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCrear)
                        .addComponent(lblAdvertencia)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Metodo que se ejecuta si se presiona el boton cancelar
     * @param evt Evento que dispara el metodo
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    /**
     * Metodo que se ejecuta si se presiona el boton crear
     * @param evt Evento que dispara el metodo
     */
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        //Se declara objeto de la clase usuario
        
        Usuario objUsuario;
        
        //Se guarda el nombre de usuario ingresado en una cadena de texto
        String username=txtNomUsuario.getText();
        
        //Se instancia la clase controlador para hacer uso de ella
       
        
        //Se consulta si el nombre de usuario ya existe en la base de datos
        System.out.println("llegamos antes de la consulta");
        objUsuario=objControl.consultUser(username, 1);
        
        
        //Si no existe, se capturan los demas datos de la interfaz,
        //se envian al controlador para guardarlos y se informa al
        //usuario
        if(objUsuario.getPassword()==null){
            String nombres=txtNombres.getText();
            String apellidos=txtApellidos.getText();
            String contrasena=txtContrasena.getText();
            String email=txtMail.getText();
            String cedula=txtCedula.getText();
            String perfil=comboPerfil.getSelectedItem().toString();
            int numConvocatoria=comboConvocatoria.getSelectedIndex();
            
            
            Convocatoria convo;
            if(perfil.equals("Administrador")){
                convo=null;
                
            }else{
                convo= objConvocatoria.readConv(nomConvocatorias[numConvocatoria]);
                System.out.println("nombre de la convo:"+convo);
            }
            int result = objControl.createUser(cedula, nombres, apellidos, username, contrasena, email, perfil,convo);
            
            if(result == -1 || result == -2){
                JOptionPane.showMessageDialog(this, "Posiblemente estas ingresando a una persona que ya existe \nIntenta ingresar a una persona diferente (cedula diferente)\nSi el problema persiste ha ocurrido un error en la base de datos,consulta al personal encargado","Error!",JOptionPane.ERROR_MESSAGE);
            }else{
                //Se imprime el mensaje para informar el exito de la operacion
                JOptionPane.showMessageDialog(this, "El usuario "+ username+" se ha creado con exito", "Mensaje de exito",JOptionPane.INFORMATION_MESSAGE);
                //Cerramos la ventana
                this.dispose();
            }
                    
            
            
            
        }else{
            if(objUsuario.getState()==false){
                //Si ya existe el nombre de usuario en la base de datos se informa al
                //usuario del error
                JOptionPane.showMessageDialog(this, "El nombre de usuario "+username+" se encuentra\ninactivo, para reactivarlo visite la seccion\neditar usuario del panel administrador");
            }else{
                //Si ya existe el nombre de usuario en la base de datos se informa al
                //usuario del error
                JOptionPane.showMessageDialog(this, "El nombre de usuario "+username+" ya existe");
            }
            
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void comboPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPerfilActionPerformed
        // TODO add your handling code here:
        int seleccion=comboPerfil.getSelectedIndex()+1;
        if(seleccion==3){
            lblConvocatoria.setVisible(false);
            comboConvocatoria.setVisible(false);
            lblAdvertencia.setVisible(false);
            btnCrear.setEnabled(true);
        }else{
            if(hayConvocatorias==false){
                lblConvocatoria.setVisible(false);
                comboConvocatoria.setVisible(false);
                lblAdvertencia.setVisible(true);
                btnCrear.setEnabled(false);
            }else{
                btnCrear.setEnabled(true);
                lblAdvertencia.setVisible(false);
                lblConvocatoria.setVisible(true);
                comboConvocatoria.setVisible(true);
            }
        }
    }//GEN-LAST:event_comboPerfilActionPerformed

    private void consultaConvocatorias(){
        Convocatoria[] listaConvocatorias;
        listaConvocatorias=objConvocatoria.listConv();
        int longitud=listaConvocatorias.length;
        hayConvocatorias=false;
        if(longitud>=1){
            hayConvocatorias=true;
        }
    }
    
    private void muestraConvocatorias(){
        Convocatoria[] listaConvocatorias;
        listaConvocatorias=objConvocatoria.listConv();
        int longitud=listaConvocatorias.length;
        nomConvocatorias=new String[longitud];
        for(int i=0; i<longitud; i++){
            String nombre=listaConvocatorias[i].getName();
            System.out.println(nombre);
            nomConvocatorias[i]=nombre;
        }
        comboConvocatoria.setModel(new javax.swing.DefaultComboBoxModel(nomConvocatorias));
    }
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCrearUsuario().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox comboConvocatoria;
    private javax.swing.JComboBox comboPerfil;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAdvertencia;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblConvocatoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblNomUsuario;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNomUsuario;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
